import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TrpcProvider } from './api/trpc/client/trpc-provider';
import AntdProvider from './shared/providers/AntdProvider';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { SessionProvider } from "next-auth/react"

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <TrpcProvider>
          <AntdRegistry>
            <AntdProvider>
              {/* <SessionProvider> */}
              {children}
              {/* </SessionProvider> */}
            </AntdProvider>
          </AntdRegistry>
        </TrpcProvider>
      </body>
    </html>
  );
}
